### ISSUE TITLE
默认object没有添加child的加号，重复选中后才有

### ISSUE THREAD

**Issue by mumuwen520** [lin-mt/json-schema-editor-antd#4]
默认object没有添加child的加号，重复选中后才有

**Comment by lin-mt** [comment]
```typescript
export default () => {
  const [val, setVal] = useState({
    type: 'object',
  });

  console.log(val, 'val');

  return (
    <div style={{ width: '90%' }}>
      <JsonSchemaEditor
        mock
        onChange={(value) => {
          setVal(value);
        }}
      />
    </div>
  );
};
```

我这里是有加号的，你能提供下你的默认值吗

**Comment by lin-mt** [comment]
```typescript
export default () => {
  const [val, setVal] = useState({});

  console.log(val, 'val');

  return (
    <div style={{ width: '90%' }}>
      <JsonSchemaEditor
        mock
        onChange={(value) => {
          setVal(value);
        }}
      />
    </div>
  );
};
```
这样也是有加号的吧，在这个文件里面是可以的，还是说用项目引入之后，效果跟这个文件里面的效果不一样？
<img width="184" alt="image" src="https://user-images.githubusercontent.com/58337359/187965564-ab0e9d51-b46b-4b8d-9671-53cb77c625ed.png">

**Comment by XueMeijing** [comment]
> ```ts
> export default () => {
>   const [val, setVal] = useState({});
> 
>   console.log(val, 'val');
> 
>   return (
>     <div style={{ width: '90%' }}>
>       <JsonSchemaEditor
>         mock
>         onChange={(value) => {
>           setVal(value);
>         }}
>       />
>     </div>
>   );
> };
> ```
> 
> 这样也是有加号的吧，在这个文件里面是可以的，还是说用项目引入之后，效果跟这个文件里面的效果不一样？ <img alt="image" width="184" src="https://user-images.githubusercontent.com/58337359/187965564-ab0e9d51-b46b-4b8d-9671-53cb77c625ed.png">

我试了下是因为你这里JsonSchemaEditor没有传data={val}, 当作第三方组件用的时候有的人可能会赋初值是空对象

**Comment by lin-mt** [comment]
v0.1.6 已修复
