### ISSUE TITLE
对象加子节点的时候会同时新增一个兄弟节点， title和discription输入的时候会报错

### ISSUE THREAD

**Issue by XueMeijing** [lin-mt/json-schema-editor-antd#6]
1. 对象加子节点的时候会同时新增一个兄弟节点
2. 除了root节点，剩下的其他节点的title和discription输入的时候会报错，输入框变[Object Object],报错 TypeError: Converting circular structure to JSON
在arco demo上可以直接复现
https://arco.design/material/detail/?name=@quiet-front-end/json-schema-editor-antd

**Comment by lin-mt** [comment]
0.1.5 已修复
