### ISSUE TITLE
schema的key的长度最低是1，删除的时候提示 FieldName can not empty.

### ISSUE THREAD

**Issue by XueMeijing** [lin-mt/json-schema-editor-antd#9]
更改的时候不是很方便，要全选之后才能修改，有的人可能不知道，用删除键一个一个删，这样第一个就删不掉了。

我目前是是把FieldInput -> handleChange 的value.length === 0判断去掉了，然后在表单里增加判断key不能为空，不知道这样改会不会影响其他地方

```
<Form.Item
  name={[1, 'schema']}
  rules={[
    ({}) => ({
      validator(_, value) {
        if (value) {
          let index = 0;
          let validateFlag = true;
          JSON.stringify(value, (k, v) => {
            // 键值不能为空
            if (index !== 0 && k === '') {
              validateFlag = false;
            }
            index++;
            return v;
          });
          if (validateFlag) {
            return Promise.resolve();
          } else {
            return Promise.reject(new Error('key值不能为空'));
          }
        }
      },
    }),
  ]}
>
  <WrappedJsonSchemaEditor />
</Form.Item>
```

![image](https://user-images.githubusercontent.com/35559153/194699399-39b52877-053b-409e-b79d-a8ad9ae043a5.png)

![image](https://user-images.githubusercontent.com/35559153/194699420-5efe80a0-aaa5-43e4-8215-aef3f0519cd3.png)

**Comment by lin-mt** [comment]
0.1.16 修复了哈，全红不太友好，无法准确定位到是哪个输入框的问题，全红是钉钉里面的方案效果吗

**Comment by XueMeijing** [comment]
> 

是的，钉钉里是全红的😂

**Comment by lin-mt** [comment]
> > 
> 
> 是的，钉钉里是全红的😂

我的解决方案怎么样，比钉钉的好吧（快夸我～）😄

**Comment by XueMeijing** [comment]
> 

你可真是个小天才哈哈哈
